apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    uid: postgres-dw
    access: proxy
    url: postgres:5432
    user: user
    jsonData:
      database: world_cup_dw
      sslmode: disable
      postgresVersion: 1400
    secureJsonData:
      password: password
    isDefault: true

  - name: Prometheus
    type: prometheus
    uid: prometheus-dw
    access: proxy
    url: http://prometheus:9090
    isDefault: false
